# ci/github-actions.yml
name: CI – Avatar Renderer Pod

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install linting tools
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black

      - name: Run flake8
        run: flake8 app tests

      - name: Check formatting with Black
        run: black --check .

  test:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    needs: lint
    services:
      # No additional services required for CPU‑only smoke tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q

  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to IBM Cloud Container Registry
        uses: docker/login-action@v2
        with:
          registry: icr.io
          username: apikey
          password: ${{ secrets.IBMCR_APIKEY }}

      - name: Build Docker image
        run: |
          IMAGE=icr.io/videogenie/avatar-renderer:${{ github.sha }}
          docker build --pull -t $IMAGE .

      - name: Push Docker image
        run: |
          IMAGE=icr.io/videogenie/avatar-renderer:${{ github.sha }}
          docker push $IMAGE

  deploy:
    name: (Optional) Deploy Chart via Argo CD
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4
        with:
          path: infra

      - name: Install IBM Cloud CLI & Plugins
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud plugin install container-registry -f
          ibmcloud plugin install kubernetes-service -f

      - name: Log in to IBM Cloud
        run: ibmcloud login --apikey ${{ secrets.IBM_CLOUD_APIKEY }} -r eu-de

      - name: Configure cluster
        run: |
          ibmcloud ks cluster config --cluster vg-cluster

      - name: Update Helm chart values
        run: |
          TAG=${{ github.sha }}
          yq e '.image.tag = strenv(TAG)' -i charts/avatar-renderer/values.yaml

      - name: Deploy via Helm
        run: |
          helm upgrade --install avatar-renderer charts/avatar-renderer \
            --namespace videogenie --create-namespace \
            --set image.repository=icr.io/videogenie/avatar-renderer \
            --set image.tag=${{ github.sha }}
